sobKern=[-1 0 1; - 2 0 2; -1 0 1];
gausKern= fspecial("gaussian",16,2.5);
dogKern=conv2(gausKern,sobKern);
surf(gausKern);
surf(dogKern);
hpimg=im2double(imread("question 1/HP.png"));
lpimg=im2double(imread("question 1/LP.png"));
hpgaus=imfilter(hpimg,gausKern);
lpgaus=imfilter(lpimg,gausKern);
hpgausfft=abs(fftshift(fft2(hpgaus))/100);
lpgausfft=abs(fftshift(fft2(lpgaus))/100);
dogfft=fft2(dogKern,500,500);
hpfft=fft2(hpimg);
lpfft=fft2(lpimg);
hpdogfreq=hpfft .*dogfft;
lpdogfreq=lpfft .*dogfft;
hpdogspacial=ifft2(hpdogfreq);
lpdogspacial=ifft2(lpdogfreq);
imshow(abs(fftshift(hpdogspacial))/100);
imshow(abs(fftshift(lpdogspacial))/100);
